.PHONY: tweets , snake

tweets: tweets_generator.c markov_chain.h markov_chain.c linked_list.c linked_list.h
	gcc -Werror -Wall -Wextra -Wvla  -std=c99 -o output_tweet

snake: snakes_and_ladders.c markov_chain.h markov_chain.c linked_list.c linked_list.h
	gcc -Werror -Wall -Wextra -Wvla -std=c99 -o output_snake










